#!/usr/bin/env python3
"""Offline fixture implementing the final-output surfaces of Codex and Claude CLIs."""

from __future__ import annotations

import json
import sys
import time
from pathlib import Path


def task_from_prompt(prompt: str) -> dict:
    marker = "AgentTask:\n"
    if marker not in prompt:
        raise ValueError("missing AgentTask marker")
    return json.loads(prompt.split(marker, 1)[1])


def changed_file(task: dict, objective: str) -> str | None:
    if task["mode"] != "worktree_patch":
        return None
    if "protected-change" in objective:
        return "config/gate-policies.v1.yaml"
    if "out-of-scope-change" in objective:
        return "outside.txt"
    allowed = task["allowed_write_paths"][0]
    return allowed if Path(allowed).suffix else f"{allowed}/agent.txt"


def main() -> int:
    provider = sys.argv[1]
    args = sys.argv[2:]
    if "--version" in args:
        print(f"fake-{provider} 1.0")
        return 0
    prompt = sys.stdin.read()
    task = task_from_prompt(prompt)
    objective = task["objective"].lower()
    if "sleep-provider" in objective:
        time.sleep(5)
    if "excess-output" in objective:
        print("x" * (int(task["max_output_bytes"]) + 4096))
        return 0
    if "provider-error" in objective:
        if "structured-provider-error" in objective and provider == "claude":
            print(
                json.dumps(
                    {
                        "type": "result",
                        "subtype": "error_max_budget_usd",
                        "session_id": "fixture-failed-session",
                        "total_cost_usd": 0.25,
                        "terminal_reason": "max_budget_usd",
                    }
                )
            )
            return 7
        print("fixture provider failed", file=sys.stderr)
        return 9
    if "malformed-result" in objective:
        print("not-json")
        return 0

    changed = changed_file(task, objective)
    if changed is not None:
        path = Path(changed)
        path.parent.mkdir(parents=True, exist_ok=True)
        content = (
            "x" * (int(task["max_output_bytes"]) + 512)
            if "oversized-patch" in objective
            else "generated by fixture\n"
        )
        path.write_text(content, encoding="utf-8")
    result = {
        "schema_version": 1,
        "task_id": "wrong-agent-task" if "wrong-task" in objective else task["task_id"],
        "status": "blocked" if "blocked-result" in objective else "complete",
        "summary": (
            "x" * (int(task["max_output_bytes"]) + 512)
            if "oversized-structured-result" in objective
            else "Fixture provider completed the bounded task."
        ),
        "findings": (
            [
                {
                    "severity": "P1",
                    "title": "Missing evidence fixture",
                    "evidence_paths": ["missing-evidence.txt"],
                    "recommendation": "Provide real evidence.",
                }
            ]
            if "missing-evidence" in objective
            else []
        ),
        "changed_paths": (
            ["README.md"] if "readonly-change-claim" in objective else ([changed] if changed else [])
        ),
        "next_actions": [],
        "assumptions": [],
        "issues": ["fixture blocker"] if "blocked-result" in objective else [],
    }
    if provider == "codex":
        output_index = args.index("--output-last-message") + 1
        Path(args[output_index]).write_text(json.dumps(result), encoding="utf-8")
        print(json.dumps({"type": "thread.started", "thread_id": "fixture-codex-session"}))
    elif provider == "claude":
        if "fenced-result" in objective:
            print(
                json.dumps(
                    {
                        "type": "result",
                        "subtype": "success",
                        "session_id": "fixture-claude-session",
                        "total_cost_usd": 0.01,
                        "result": f"```json\n{json.dumps(result)}\n```\nValidated result.",
                    }
                )
            )
            return 0
        print(
            json.dumps(
                {
                    "type": "result",
                    "subtype": "success",
                    "session_id": "fixture-claude-session",
                    "total_cost_usd": 0.01,
                    "structured_output": result,
                }
            )
        )
    else:
        raise ValueError(f"unknown fixture provider: {provider}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
